# Documentation: https://github.com/codecov/support/wiki/Codecov-Yaml
codecov:
  notify:
    after_n_builds: 1  # send notifications after the first upload

coverage:
  precision: 3
  round: down
  range: 80...100

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project: true
    patch: true
    changes: true

comment: false
